config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   resources :users do
   	collection do
   		get :listbeds
         get 'previous', :to => 'users#previous'
         get 'checkout/:id', :to => 'users#checkout'
         get 'bill/:id', :to =>'users#bill'
         get 'register', :to =>'users#register'
         get 'login', :to => 'users#login'
         post 'login', :to => 'users#validatelogin'
   	end
   end	
   resources :admins do
      collection do
         get 'approvecheckin/:id/:qt', :to => 'admins#approvecheckin'
         get 'approvecheckout/:id/:qt', :to => 'admins#approvecheckout'
         get 'disapprovecheckout/:id', :to => 'admins#disapprovecheckout'
         get 'disapprovecheckin/:id', :to => 'admins#disapprovecheckin'
         get 'error', :to => 'admin#error'
      end
   end
   resources :mains
   resources :beds

   resources :requests do
   	collection do
   		get 'create/:val', to: 'resources#create'
   	end
   end

   resources :mains do
      collection do
         
      end
   end

   get '/', to: 'mains#index'
   get '/logout', to: 'users#logout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bed.rb
class Bed < ApplicationRecord
end

app/models/request.rb
class Request < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def index
		@requests = Request.where(requestcompleted: false)
	end

	def show 

	end

	def approvecheckin
		@request = Request.where(id: params[:id])[0]
		@request.checkedin = true
		@request.checkintime = DateTime.now
		@request.requestcompleted = true
		@bed = Bed.where(bedtype: @request.bedtype)[0]
		@one = Integer(params[:qt])
		@two = Integer(@bed.quantity)
		@ok = false
		if @bed.quantity >= Integer(params[:qt])
			@bed.quantity -= Integer(params[:qt])
			@ok = true
			@bed.save
			@request.save
			redirect_to :controller => 'admins', :action => 'index'
		else 
			render :error
		end
		#@bed.save
		#@request.save
		#redirect_to :controller => 'admins', :action => 'index'
	end

	def approvecheckout
		@request = Request.where(id: params[:id])[0]
		@request.checkedout = true
		@request.checkouttime = DateTime.now
		@request.requestcompleted = true
		@bed = Bed.where(bedtype: @request.bedtype)[0]
		@bed.quantity += Integer(params[:qt])
		@bed.save
		@request.save
		redirect_to :controller => 'admins', :action => 'index'
	end

	def disapprovecheckin
		@request = Request.find(params[:id]).destroy
		redirect_to :controller => 'admins', :action => 'index'
	end

	def disapprovecheckout
		@request = Request.where(id: params[:id])[0]
		@request.requestcompleted = true
		@request.save
		redirect_to :controller => 'admins', :action => 'index'
	end 

	def error
		@error = "Some error occured."
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beds_controller.rb
class BedsController < ApplicationController
	def index
		@requests = Request.where(requestcompleted: false)
		@beds = Bed.all
	end

	def edit
		@bed = Bed.find(params[:id])
		@requests = Request.where(requestcompleted: false)
	end

	def update
		@bed = Bed.find(params[:id])
		if @bed.update(bed_params)
	      redirect_to beds_url
	    else
	      render :edit
	    end
	end

	def bed_params
		params.require(:bed).permit(:bedtype, :quantity)
	end
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
	def index

	end

	def register

	end

	def login
		
	end

	def create
		@user = User.new
		@user.username = params[:username]
		@user.password = params[:password]
		@user.usertype = "normal"
		# if @user.save
	 #      redirect_to 'http://localhost:3000/login'
	 #    else
	 #      render :register
	 #    end
	end

	def validatelogin

	end

	def logout

	end

	

end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	def new

	end

	def show
		@requests = Request.where(requestcompleted: false, username: session[:username])
		@bed = Bed.find(params[:id])
		@request = Request.new :username => "hameed", :bedtype => @bed.bedtype, :requestcompleted =>false, :checkedin => false, :checkedout =>false
	end

	def create
		@request = Request.new(request_params)
		@request.username = session[:username]
	    if @request.save
	      redirect_to 'http://localhost:3000/users'
	    else
	      render :new
	    end
	end

	def request_params
		params.require(:request).permit(:username, :bedtype, :quantity, :requestcompleted, :checkedin, :checkedout, :checkintime, :checkouttime)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@requests = Request.where(requestcompleted: false, username: session[:username])
	end

	def listbeds
		@requests = Request.where(requestcompleted: false, username: session[:username])
		@beds = Bed.all
	end

	def previous
		@requests = Request.where(requestcompleted: true, username: session[:username])
	end

	def checkout
		@request = Request.where(id: params[:id])[0]
		@request.requestcompleted = false
		@request.save
		redirect_to :controller => 'users', :action => 'previous'
	end

	def bill
		@request = Request.where(id: params[:id])[0]
		@cost = Bed.where(bedtype: @request.bedtype)[0].cost
		@totaltime = (Time.parse(@request.checkouttime.to_s)-Time.parse(@request.checkintime.to_s))/(60*60)
	end

	def register
		@user = User.new
	end

	def login
		
	end

	def create
		@user = User.new(user_params)
		@user.usertype = "normal"
		if @user.save
	      redirect_to 'http://localhost:3000/users/login'
	      return
	    else
	      redirect_to 'http://localhost:3000/users/register'
	      return
	    end
	end

	def validatelogin
		@user = User.where(username: params[:username], password: params[:password])
		@ok = false
		if @user.count == 0
			redirect_to 'http://localhost:3000/users/login'
			return
		end
		@user = @user[0]
		session[:username] = params[:username]
		if @user.usertype == "admin"
			session[:usertype] = "admins"
			redirect_to 'http://localhost:3000/admins'
			return
		else 
			session[:usertype] = "users"
			redirect_to 'http://localhost:3000/users'
			return
		end
	end

	def logout
		session.delete(:username)
		session.delete(:usertype)
		redirect_to 'http://localhost:3000'
	end

	def user_params
		params.require(:user).permit(:username, :password, :usertype)
	end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beds_helper.rb
module BedsHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/approvecheckin.html.erb
<%= @one %>
<br>
<%= @two %>
<br>
<%= @ok %>

app/views/admins/error.html.erb
<% if(session[:username] == nil or session[:usertype] != "admins") %>
<script type="text/javascript">
    window.location.href="/" 
</script>
<% else %>

Some error occured. Check if you have approved an invalid request.

<% end %>

app/views/admins/index.html.erb
<% if(session[:username] == nil or session[:usertype] != "admins") %>
<script type="text/javascript">
    window.location.href="/" 
</script>
<% else %>

<div class="row" style=" height: 100%;">
		    <div class="col-md-2" style="background: #1e2126; padding: 0;">
		      <h2 style="color: #4e555d; font-weight: lighter; text-align: center; padding-top: 30px;"><span style="color: #ab9cd7; font-size: 40px;">+ </span><%= truncate(session[:username], :length => 6) %></h2>
		      <a href="/beds" class="purple-inside-black">Modify beds</a>
		      <div href="#" class="heading-inside-black">NOTIFICATIONS</div>
		      <a href="#" class="option-inside-black highlighted-1">Inbox (<%= @requests.count %>)</a>
<!-- 		      <a href="previous.html" class="option-inside-black">History</a> -->
		      <a href="http://localhost:3000/logout" class="app-button purple-only" style="margin-top: 100px;">Logout</a>
		    </div>
		    
		    <div class="col-md" style="width: 99%; height: 100%; background: #ffffff; margin: 0px; padding: 0px; margin-left: 3px; overflow: auto;">
		      <h2 style="color: #4e555d; font-weight: lighter; padding-top: 40px; padding-left: 40px;">Inbox</h2>
		      <div class="hr" style="margin-top: 35px;"></div>
		      <table style="width: 100%; text-align: center;" class="fixed_header">
		      	<thead >
			      <tr style="background: #f1f2f4; height: 40px; color: #4e555d;">
			      	<th>ID</th>
			      	<th>User</th>
			      	<th>Bed</th>
			      	<th>Quantity</th>
			      	<th>Type</th>
			      	<th>Approve</th>
			      	<th>Disapprove</th>
			      </tr>
			     </thead>
			     <tbody>
			     <% @requests.each do |r| %>
			     	<tr style="height: 40px; color: #4e525b;">
			     	<td><%= r.id %></td>
			      	<td><%= r.username %></td>
			      	<td><%= r.bedtype %></td>
			      	<td><%= r.quantity %></td>
			      	<td>
			      		<% if (r.checkedin) %>
			      			<%= "Checkout" %>
			      		<% else %>
			      			<%= "Checkin" %>
			      		<% end %>
			      	</td>
			      	<td>
			      		<% if (r.checkedin) %>
			      			<a href="http://localhost:3000/admins/approvecheckout/<%= r.id %>/<%= r.quantity %>" class="app-button purple-only">Approve</a></td>
			      		<% else %>
			      			<a href="http://localhost:3000/admins/approvecheckin/<%= r.id %>/<%= r.quantity %>" class="app-button purple-only">Approve</a></td>
			      		<% end %>
			      	</td>
			      	<td>
			      		<% if (r.checkedin) %>
			      			<a href="http://localhost:3000/admins/disapprovecheckout/<%= r.id %>" class="app-button">Disapprove</a></td>
			      		<% else %>
			      			<a href="http://localhost:3000/admins/disapprovecheckin/<%= r.id %>" class="app-button">Disapprove</a></td>
			      		<% end %>
			      	</td>
			      </tr>
			     <% end %>
			     </tbody>
		      </table>
		    </div>
		</div>

<% end %>

app/views/admins/listbeds.html.erb
<% if(session[:username] == nil or session[:usertype] != "admins") %>
<script type="text/javascript">
    window.location.href="/" 
</script>
<% else %>

<div class="row" style=" height: 100%;">
    <div class="col-md-2" style="background: #1e2126; padding: 0;">
      <h2 style="color: #4e555d; font-weight: lighter; text-align: center; padding-top: 30px;"><span style="color: #ab9cd7; font-size: 40px;">+ </span><%= truncate(session[:username], :length => 6) %></h2>
      <a href="#" class="purple-inside-black">Modify beds</a>
      <div href="#" class="heading-inside-black">NOTIFICATIONS</div>
      <a href="/admins" class="option-inside-black">Inbox (<%= @requests.count %>)</a>
      <a href="http://localhost:3000/logout" class="app-button purple-only" style="margin-top: 100px;">Logout</a>
    </div>
    
    <div class="col-md" style="width: 99%; height: 100%; background: #ffffff; margin: 0px; padding: 0px; margin-left: 3px; overflow: auto;">
      <h2 style="color: #4e555d; font-weight: lighter; padding-top: 40px; padding-left: 40px;">Bed Management</h2>
      <div class="hr" style="margin-top: 35px;"></div>
      <table style="width: 100%; text-align: center;" class="fixed_header">
      	<thead >
	      <tr style="background: #f1f2f4; height: 40px; color: #4e555d;">
	      	<th>Bed</th>
	      	<th>Quantity</th>
	      	<th>Cost</th>
	      	<th>Modify</th>
	      </tr>
	     </thead>
	     <tbody>
	     <% @beds.each do |b| %>
	     	<tr style="height: 40px; color: #4e525b;">
	     	<td><%= b.cost %></td>
	      	<td><%= b.bedtype %></td>
	      	<td><%= b.quantity %></td>
	      	<td><a href="modifybed.html" class="app-button purple-only">Modify</a></td>
	      </tr>
	     <% end %>
	      
	     </tbody>
      </table>
    </div>
</div>

<% end %>

app/views/beds/edit.html.erb
<% if(session[:username] == nil or session[:usertype] != "admins") %>
<script type="text/javascript">
    window.location.href="/" 
</script>
<% else %>

<!doctype hmtl>
<html>
  <head>
    <title>Mail</title>
    <link rel="stylesheet" type="text/css" href="bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="styles.css" />
  </head>
  <body>
    <div class="row" style=" height: 100%;">
        <div class="col-md-2" style="background: #1e2126; padding: 0;">
          <h2 style="color: #4e555d; font-weight: lighter; text-align: center; padding-top: 30px;"><span style="color: #ab9cd7; font-size: 40px;">+ </span><%= truncate(session[:username], :length => 6) %></h2>
          <a href="http://localhost:3000/beds" class="purple-inside-black">Modify beds</a>
          <div href="#" class="heading-inside-black">NOTIFICATIONS</div>
          <a href="http://localhost:3000/admins" class="option-inside-black">Inbox (<%= @requests.count %>)</a>
          <a href="http://localhost:3000/logout" class="app-button purple-only" style="margin-top: 100px;">Logout</a>
        </div>
        
        <div class="col-md" style="width: 99%; height: 100%; background: #ffffff; margin: 0px; padding: 0px; margin-left: 3px; overflow: auto;">
          <h2 style="color: #4e555d; font-weight: lighter; padding-top: 40px; padding-left: 40px;">Enter details of <%= @bed.bedtype %> beds</h2>
          <div class="hr" style="margin-top: 35px; backgorund: #0F0F0F"></div>
          <%= form_with model: @bed, html: {style: "width: 50%; margin: auto;"}, local: true do |form| %>
            <div class="form-group">
              <%= form.hidden_field  :bedtype, class: "form-control" %><br>
            </div>

            <div class="form-group">
              <%= form.label :quantity %><br>
              <%= form.text_field :quantity, class: "form-control" %><br>
            </div>

            <div class="form-group">
              <%= form.label :cost %><br>
              <%= form.text_field :cost, class: "form-control" %><br>
            </div>

            <div class="form-group">
              <%= form.submit "Modify", class: "form-control" %>
            </div>
          <% end %>
        </div>
    </div>
  </body>
</html>

<% end %>

app/views/beds/index.html.erb
<% if(session[:username] == nil or session[:usertype] != "admins") %>
<script type="text/javascript">
    window.location.href="/" 
</script>
<% else %>


<div class="row" style=" height: 100%;">
    <div class="col-md-2" style="background: #1e2126; padding: 0;">
      <h2 style="color: #4e555d; font-weight: lighter; text-align: center; padding-top: 30px;"><span style="color: #ab9cd7; font-size: 40px;">+ </span><%= truncate(session[:username], :length => 6) %></h2>
      <a href="#" class="purple-inside-black">Modify beds</a>
      <div href="#" class="heading-inside-black">NOTIFICATIONS</div>
      <a href="http://localhost:3000/admins" class="option-inside-black">Inbox (<%= @requests.count %>)</a>
      <a href="http://localhost:3000/logout" class="app-button purple-only" style="margin-top: 100px;">Logout</a>
    </div>
    
    <div class="col-md" style="width: 99%; height: 100%; background: #ffffff; margin: 0px; padding: 0px; margin-left: 3px; overflow: auto;">
      <h2 style="color: #4e555d; font-weight: lighter; padding-top: 40px; padding-left: 40px;">Bed Management</h2>
      <div class="hr" style="margin-top: 35px;"></div>
      <table style="width: 100%; text-align: center;" class="fixed_header">
      	<thead >
	      <tr style="background: #f1f2f4; height: 40px; color: #4e555d;">
	      	<th>Bed</th>
	      	<th>Quantity</th>
	      	<th>Cost</th>
	      	<th>Modify</th>
	      </tr>
	     </thead>
	     <tbody>
	     <% @beds.each do |b| %>
	     	<tr style="height: 40px; color: #4e525b;">
	      	<td><%= b.bedtype %></td>
	      	<td><%= b.quantity %></td>
	      	<td><%= b.cost %></td>
	      	<td><%= link_to "Modify", edit_bed_path(b), class: "btn btn-primary app-button purple-only on-hover-purple-only", style: "border: none;" %></td>
	      	
	      </tr>
	     <% end %>
	      
	     </tbody>
      </table>
    </div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE hmtl>
<html>
  <head>
    <title>Hospitalbedmanagementapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mains/create.html.erb
<%= @user.name %><br>
<%= @user.password %><br>
<%= @user.usertype %>

app/views/mains/index.html.erb
<style type="text/css">
	body {
		background: #1e2126;
	}
</style>
<div class="container">
	<h1 style="color: #FFFFFF; font-weight: lighter; text-align: center; margin-top: 100px;">Welcome to the <span style="color: #ab9cd7; font-size: 40px;">+ </span> Bed Management System.</h1>
	<h3 style="color: #FFFFFF; font-weight: lighter; text-align: center;">Please login to use the system.</h3>
	<div class="row" style=" height: 100%; margin-top: 100px;">
		<div class="col-md-2" style="background: #1e2126; padding: 0; margin: auto; margin-top: 100px; margin-bottom: 100px;">
			<a href="http://localhost:3000/users/register" class="purple-inside-black">Register</a>
		</div>
		<div class="col-md-2" style="background: #1e2126; padding: 0; margin: auto; margin-top: 100px; margin-bottom: 100px;">
			<a href="http://localhost:3000/users/login" class="turqoise-inside-black">Login</a>
		</div>
	</div>
</div>

app/views/mains/login.html.erb
<!doctype html>
<html>
	<head>
		<title>Mail</title>
		<link rel="stylesheet" type="text/css" href="bootstrap.min.css" />
		<link rel="stylesheet" type="text/css" href="styles.css" />
	</head>
	<body style="background: #1e2126">
		<div class="container" style="width: 400px;"> 
			<div class="card" style=" margin-left: auto; margin-right: auto; margin-top: 150px;">
			  <div class="card-body" style="margin: 20px;">
			    <h4 style="padding-bottom: 10px;">Please Register Below</h4>
					<%= form_with model: @request, local: true do |form| %>
		          		<div class="form-group">
			              <%= form.label :username %><br>
			              <%= form.text_field :username, class: "form-control", placeholder: "Enter Username" %>
			              <small id="emailHelp" class="form-text text-muted">Username need not be an email ID.</small>
			            </div>
			            <div class="form-group">
			              <%= form.label :password %><br>
			              <%= form.text_field :password, class: "form-control", placeholder: "Password" %>
			            </div>

			            <div class="form-group">
			              <%= form.submit "Login", class: "btn btn-primary app-button purple-only on-hover-purple-only", style: "border: none; background: #1abc9c;" %>
			            </div>
		          	<% end %>
			    <!---
			    <form>
				  <div class="form-group">
				    <label for="exampleInputEmail1">Username</label>
				    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username">
				    
				  </div>
				  <div class="form-group">
				    <label for="exampleInputPassword1">Password</label>
				    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
				  </div>
				  <button type="submit" class="btn btn-primary app-button purple-only on-hover-purple-only" style="border: none;">Register</button>
				</form>
				-->
			  </div>
			</div>
		</div>
	</body>
</html>

app/views/mains/register.html.erb
<!doctype html>
<html>
	<head>
		<title>Mail</title>
		<link rel="stylesheet" type="text/css" href="bootstrap.min.css" />
		<link rel="stylesheet" type="text/css" href="styles.css" />
	</head>
	<body style="background: #1e2126">
		<div class="container" style="width: 400px;"> 
			<div class="card" style=" margin-left: auto; margin-right: auto; margin-top: 150px;">
			  <div class="card-body" style="margin: 20px;">
			    <h4 style="padding-bottom: 10px;">Please Register Below</h4>
					<%= form_with model: @request, local: true do |form| %>
						<%= form.label :usertype %><br>
						<%= form.hidden_field :usertype %>
		          		<div class="form-group">
			              <%= form.label :username %><br>
			              <%= form.text_field :username, class: "form-control", placeholder: "Enter Username" %>
			              <small id="emailHelp" class="form-text text-muted">Username need not be an email ID.</small>
			            </div>
			            <div class="form-group">
			              <%= form.label :password %><br>
			              <%= form.text_field :password, class: "form-control", placeholder: "Password" %>
			            </div>

			            <div class="form-group">
			              <%= form.submit "Register", class: "btn btn-primary app-button purple-only on-hover-purple-only", style: "border: none;" %>
			            </div>
		          	<% end %>
			    <!---
			    <form>
				  <div class="form-group">
				    <label for="exampleInputEmail1">Username</label>
				    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Username">
				    
				  </div>
				  <div class="form-group">
				    <label for="exampleInputPassword1">Password</label>
				    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
				  </div>
				  <button type="submit" class="btn btn-primary app-button purple-only on-hover-purple-only" style="border: none;">Register</button>
				</form>
				-->
			  </div>
			</div>
		</div>
	</body>
</html>

app/views/requests/show.html.erb
<!doctype hmtl>
<html>
  <head>
    <title>Mail</title>
    <link rel="stylesheet" type="text/css" href="bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="styles.css" />
  </head>
  <body>
    <div class="row" style=" height: 100%;">
        <div class="col-md-2" style="background: #1e2126; padding: 0;">
          <h2 style="color: #4e555d; font-weight: lighter; text-align: center; padding-top: 30px;"><span style="color: #ab9cd7; font-size: 40px;">+ </span><%= truncate(session[:username], :length => 6) %></h2>
          <a href="http://localhost:3000/users/listbeds" class="purple-inside-black">Request beds</a>
          <div href="#" class="heading-inside-black">NOTIFICATIONS</div>
          <a href="http://localhost:3000/users" class="option-inside-black">Inbox (<%= @requests.count %>)</a>
          <a href="http://localhost:3000/users/previous" class="option-inside-black">Previous</a>
          <a href="http://localhost:3000/logout" class="app-button purple-only" style="margin-top: 100px;">Logout</a>
        </div>
        
        <div class="col-md" style="width: 99%; height: 100%; background: #ffffff; margin: 0px; padding: 0px; margin-left: 3px; overflow: auto;">
          <h2 style="color: #4e555d; font-weight: lighter; padding-top: 40px; padding-left: 40px;">Enter quantity of <%= @bed.bedtype %> beds</h2>
          <div class="hr" style="margin-top: 35px; backgorund: #0F0F0F"></div>
          <%= form_with model: @request, html: {style: "width: 50%; margin: auto;"}, local: true do |form| %>
          <div>
              <%= form.hidden_field  :username %><br>
            </div>
            <div>
              <%= form.hidden_field  :bedtype %><br>
            </div>
            <div>
              <%= form.hidden_field  :requestcompleted %><br>
            </div>
            <div>
              <%= form.hidden_field  :checkedin %><br>
            </div>
            <div>
              <%= form.hidden_field  :checkintime %><br>
            </div>
            <div>
              <%= form.hidden_field  :checkedout %><br>
            </div>
            <div>
              <%= form.hidden_field  :checkouttime %><br>
            </div>
            <div class="form-group">
              <%= form.label :quantity %><br>
              <%= form.text_field :quantity, class: "form-control" %><br>
            </div>

            <div>
              <%= form.submit "Request", class: "form-control" %>
            </div>
          <% end %>
        </div>
    </div>
  </body>
</html>

app/views/users/bill.html.erb
<% if(session[:username] == nil or session[:usertype] == "admins") %>
<script type="text/javascript">
    window.location.href="/" 
</script>
<% else %>


<div class="container" style="text-align: center;">
<h2 style="padding-top: 100px;">Order ID: # <%= @request.id %></h3>
<hr>

<address>
<strong>Billed To:</strong><br>
	<%= @request.username %>
</address>
<address>
<strong>Payment Details:</strong><br>
Payment Method: Paid At Counter<br>
From: <%= Time.parse(@request.checkintime.to_s) %><br>
To: <%= Time.parse(@request.checkouttime.to_s) %><br>
Duration: <%=  @totaltime.round(2) %> Hours<br> 
Amount: $<%= (@totaltime*@cost*@request.quantity).round(2) %>
</address>
    <button class="app-button purple-only" style="border: none;" onclick="window.print();return false;">Print</button>
</div>

<% end %>

app/views/users/checkout.html.erb
Request Checkout 
<%= @requests.bedtype  %>

app/views/users/create.html.erb
<%= @user.username %><br>
<%= @user.password %><br>
<%= @user.usertype %>

app/views/users/index.html.erb
<% if(session[:username] == nil or session[:usertype] == "admins") %>
<script type="text/javascript">
    window.location.href="/" 
</script>
<% else %>

<div class="row" style=" height: 100%;">
		    <div class="col-md-2" style="background: #1e2126; padding: 0;">
		      <h2 style="color: #4e555d; font-weight: lighter; text-align: center; padding-top: 30px;"><span style="color: #ab9cd7; font-size: 40px;">+ </span><%= truncate(session[:username], :length => 6) %></h2>
		      <a href="http://localhost:3000/users/listbeds" class="purple-inside-black">Request beds</a>
		      <div href="#" class="heading-inside-black">NOTIFICATIONS</div>
		      <a href="#" class="option-inside-black highlighted-1">Inbox (<%= @requests.count %>)</a>
		       <a href="http://localhost:3000/users/previous" class="option-inside-black">Previous</a>
<!-- 		      <a href="previous.html" class="option-inside-black">History</a> -->
		      <a href="http://localhost:3000/logout" class="app-button purple-only" style="margin-top: 100px;">Logout</a>
		    </div>
		    
		    <div class="col-md" style="width: 99%; height: 100%; background: #ffffff; margin: 0px; padding: 0px; margin-left: 3px; overflow: auto;">
		      <h2 style="color: #4e555d; font-weight: lighter; padding-top: 40px; padding-left: 40px;">Inbox</h2>
		      <div class="hr" style="margin-top: 35px;"></div>
		      <table style="width: 100%; text-align: center;" class="fixed_header">
		      	<thead >
			      <tr style="background: #f1f2f4; height: 40px; color: #4e555d;">
			      	<th>ID</th>
			      	<th>User</th>
			      	<th>Bed</th>
			      	<th>Quantity</th>
			      	<th>Type</th>
			      </tr>
			     </thead>
			     <tbody>
			     <% @requests.each do |r| %>
			     	<tr style="height: 40px; color: #4e525b;">
			     	<td><%= r.id %></td>
			      	<td><%= r.username %></td>
			      	<td><%= r.bedtype %></td>
			      	<td><%= r.quantity %></td>
			      	<td>
			      		<% if (r.checkedin) %>
			      			<%= "Checkout" %>
			      		<% else %>
			      			<%= "Checkin" %>
			      		<% end %>
			      	</td>
			      </tr>
			     <% end %>
			     </tbody>
		      </table>
		    </div>
		</div>

<% end %>

app/views/users/logout.html.erb
loggedout

app/views/users/show.html.erb
admin#show

app/views/users/validatelogin.html.erb
<%= session[:usertype] %>
<br>
<%= session[:username] %>
<%= @ok %>